### ISSUE TITLE
Add xmlto package tag to devel node or appliance

### ISSUE THREAD

**Issue by rpwagner** [rocksclusters/base#12]
The xmlto package is required for building a kernel RPM from kernel.org, but is not included in the Devel Appliance defnition. The package could be added to devel.xml, or the devel-server.xml node.

**Comment by lclementi** [comment]
Added all the bootstrap packages (which include also the xmlto).
https://github.com/rocksclusters/base/commit/a68ee704cad2d7d66eb5610d36ebd5ac772ab7eb
