### ISSUE TITLE
ROCKS7: Modify behavior and/or update docs for custom partitioning

### ISSUE THREAD

**Issue by tcooper** [rocksclusters/base#20]
## Order is important...

Rocks7 custom partitioning cannot be done in `extend-<node>.xml` and possibly in `replace-<node>.xml` due to new installation behavior related to Anaconda in CentOS 7.

Example solution is to splice onto the graph with custom graph & node XML...

### /export/rocks/install/site-profiles/7.0/graphs/default/compute-partitioning.xml
```
<?xml version="1.0" standalone="no"?>

<graph>

<edge from="compute" to="compute-partitioning"/>
<order head="compute-partitioning" tail="partition"/>

</graph>
```

### /export/rocks/install/site-profiles/7.0/nodes/compute-partitioning.xml
```
<?xml version="1.0" standalone="no"?>
<kickstart>

<pre>
cat &gt;&gt; /tmp/user_partition_info &lt;&lt; 'EOF'
clearpart --all --initlabel --drives=[device_name]
zerombr
part / --fstype=ext4 --size=65536 --ondisk=[device_name]
part /scratch --fstype=ext4 --size=1 --grow --ondisk=[device_name]
EOF
</pre>

</kickstart>
```

Where `[device_name]` is `sda` or `vda` or other raw block device detected during install.

**Comment by ppapadopoulos** [comment]
Thanks, Trevor.
The most likely fix will be:

1.  define a node in the base graph called custom-partition.xml
2.  have the base graph define the order custom-partition --> partition
3. modify docs to  suggest  extend-custom-partition.xml as the place to insert custom partition code

**Comment by ppapadopoulos** [comment]
Partially completed.  Latest version has custom-partition.
Docs haven't been modified yet.

**Comment by ppapadopoulos** [comment]
Resolved by https://github.com/rocksclusters/base/commit/d50fdbe48c95078668252ab6d440a792c2174a7f
