### ISSUE TITLE
What is the difference between Apache Mesos and Rocks?

### ISSUE THREAD

**Issue by BoredBored** [rocksclusters/base#30]
I was wondering what is really the difference between the two?

**Comment by ppapadopoulos** [comment]
"Apache Mesos abstracts CPU, memory, storage, and other compute resources away from machines (physical or virtual), enabling fault-tolerant and elastic distributed systems to easily be built and run effectively."  

In other words  its a layer above physical hardware (think containers).  Rocks handles raw hardware. It would be quite straightforward to run Mesos on top of a Rocks cluster
