### ISSUE TITLE
Install new HD and make available to the nodes

### ISSUE THREAD

**Issue by rpedruzzi** [rocksclusters/base#37]
Dear All, 

I have a question which probably is an easy task.
I am new to rocks cluster and I would like to know how do I add new HD into my frontend and make it available to the nodes access it, run, read and write inside this HD.

For example... I have my export area where I work with no problem, but I do have a second HD which was mapped as /hd1. When I try to run my model inside the /hd1 (inside /hd1/test for example) using the nodes processors, I got an error saying that the mpirun of the node could not find my executable.

Can anyone help me?
I would really appreciate it.

**Comment by smhr** [comment]
Hi @rpedruzzi 

You may find [these notes](https://github.com/smhr/rocks_notes#storage) useful.

**Comment by rpedruzzi** [comment]
Hi @smhr 

Thank you so much. 
This is exactly what I need.

Regards
